### ISSUE TITLE
Are Setpoint1 and Input1 reversed in servo02.ino?

### ISSUE THREAD

**Issue by adamgreen** [XRobots/WiperMotorServo#2]
```c++
      Input1 = map(pwm,1000,2000,-255,255);
      Setpoint1 = map(pot,0,1023,-255,255);
```

I would have expected the PWM value coming from the radio receiver to be the set point. If these were flipped in the code then the motor or pot wires would probably need to be flipped too as the PID error would now have the opposite sign.

**Comment by XRobots** [comment]
Yes you are correct, I've updated that now,

thanks

**Comment by adamgreen** [comment]
Thanks for making this repository and the associated video available! It helps take the mystery out of servos and shows makers how they can extend the usage of them into areas they might not have before thought possible.
